names: 
  - xeus-cling
  - java_env
  - beakerx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - xeus-cling
  - xtensor
  - xtensor-blas
  - notebook
  - matplotlib
  - numpy
  - vpython
  - pandas
  - metakernel
  - scijava-jupyter-kernel
  - ipywidgets
  - beakerx
  - scipy
  - scikit-learn
  - pip:
    - calysto_scheme
    - metakernel
    - numpy
    - calysto
    - yasi
    - mlxtend
    - vpython
    - jupyterlab-vpython
    - scipy
    - scikit-learn
